apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-connections
  name: udaconnect-connections
spec:
  ports:
    - name: "5006"
      port: 5006
      targetPort: 5006
      nodePort: 30006
  selector:
    service: udaconnect-connections
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-connections
  name: udaconnect-connections
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-connections
  template:
    metadata:
      labels:
        service: udaconnect-connections
    spec:
      containers:
        - image: ailinelim/udaconnect-connections:latest
          name: connection
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_PORT
      restartPolicy: Always
