info:
  _postman_id: 7f683b2d-355d-45e5-8a4f-cd115612fd90
  name: Udaconnect APIs
  schema: https://schema.getpostman.com/json/collection/v2.1.0/collection.json
item:
  - name: Persons
    item:
      - name: localhost:30001/api/persons
        request:
          method: GET
          header: []
          url:
            raw: localhost:30001/api/persons/1
            host:
              - localhost
            port: '30001'
            path:
              - api
              - persons
              - '1'
        response: []
      - name: localhost:30001/api/persons
        event:
          - listen: test
            script:
              exec:
                - "{\r"
                - "    id= 100,\r"
                - "    first_name= \"Peter\",\r"
                - "    last_name= \"Lindman\",\r"
                - "    company_name= \"Changed DNA Company\"\r"
                - '}'
              type: text/javascript
        request:
          method: POST
          header:
            - key: ''
              value: '5'
              description: ok
              type: text
          body:
            mode: raw
            raw: ''
          url:
            raw: localhost:30001/api/persons
            host:
              - localhost
            port: '30001'
            path:
              - api
              - persons
        response: []
  - name: Connection
    item:
      - name: >-
          http://localhost:30001/api/persons/5/connection?distance=5&end_date=2020-12-30&start_date=2020-01-01
        request:
          method: GET
          header: []
          url:
            raw: >-
              http://localhost:30001/api/persons/5/connection?distance=5&end_date=2020-12-30&start_date=2020-01-01
            protocol: http
            host:
              - localhost
            port: '30001'
            path:
              - api
              - persons
              - '5'
              - connection
            query:
              - key: distance
                value: '5'
              - key: end_date
                value: '2020-12-30'
              - key: start_date
                value: '2020-01-01'
        response: []